---
# tasks file for JavaCac
- name: Install java
  become: yes
  yum:
    name: java-11-openjdk

- name: Create User java
  become: yes
  ansible.builtin.user:
    name: java_user
    comment: User java
    group: admin
    password: fE$RKe/V9X$796.M/2zHm96CD$cgTn/3Y.U6n82ax$gYG/fjt/b/4$AVg8n8

- name: download java app
  become: yes
  get_url:
    url: https://github.com/Ozz007/sb3t/releases/download/1.0/sb3t-ws-1.0.jar
    dest: /home/java_user/

- name: Run Jar
  shell: 'java -jar {{ JAR_PATH }}/{{ JAR_NAME }} -Xmx{{ JVM_SIZE }}'
  become_user : '{{ USER_NAME }}'
  async: 100
 